#!/bin/bash

RESERV=$(curl -s 169.254.169.254/latest/meta-data/reservation-id)
INS_ID=$(curl -s 169.254.169.254/latest/meta-data/instance-id)
ZONE=$(curl -s 169.254.169.254/latest/meta-data/placement/availability-zone)
LAUNCH_IDX=$(curl -s 169.254.169.254/latest/meta-data/ami-launch-index)

export AWS_DEFAULT_REGION=${ZONE%[a-z]}

INSTANCES=$(aws ec2 describe-instances --filter Name=reservation-id,Values=$RESERV --query Reservations[].Instances[].InstanceId --out text)
OTHER_INSTANCES=$(sed "s/$INS_ID//"<<<"$INSTANCES")

: <<KOMMENT
# my bridge
sudo ifconfig bridge0 down && sudo brctl delbr bridge0
sudo brctl addbr bridge0  && sudo ifconfig bridge0 172.17.1${LAUNCH_IDX}.1  netmask 255.255.255.0

# route to others
# read from stdin <launch-idx> <priv-ip>
# can be used as: ec2-desc-ins | route()
route() {
  while read idx ip; do
    SUBNET=172.17.1$idx
    sudo route add -net $SUBNET.0  netmask 255.255.255.0  gw $ip
  done
}

aws ec2 describe-instances --instance-ids $OTHER_INSTANCES --query Reservations[].Instances[].[AmiLaunchIndex,PrivateIpAddress] --out text | route

sudo sh -c "cat > /etc/sysconfig/docker" <<"EOF"
other_args="-b bridge0 -H unix:// -H tcp://0.0.0.0:4243"
EOF
sudo /etc/init.d/docker restart
KOMMENT

LAUNCH_IDX_OF_FIST_OTHER=$(aws ec2 describe-instances --instance-ids $OTHER_INSTANCES --query Reservations[].Instances[0].AmiLaunchIndex --out text)
SERF_JOIN_IP=172.17.1${LAUNCH_IDX_OF_FIST_OTHER}.2
echo SERF_JOIN_IP=$SERF_JOIN_IP

IMAGE=sequenceiq/ambari
#docker run -e SERF_JOIN_IP=$SERF_JOIN_IP -d --dns 127.0.0.1 -h node-$LAUNCH_IDX.mycorp.kom $IMAGE
docker run -e SERF_JOIN_IP=$SERF_JOIN_IP -d -it --dns 127.0.0.1 -h node-$LAUNCH_IDX.mycorp.kom $IMAGE /bin/bash
